project:
  type: website

resources:
  - music/ProfKam.mp3
  
website:
  title: "TRAFFIC_ACCIDENT"
  navbar:
    left:
      - text: "Shiny App"
        menu:
          - text: "ShinyApp.io"
            href: https://jhyunkim.shinyapps.io/TRAFFIC_ACCIDENT_ANALYSIS_THAILAND/
          - text: "User Guide"
            href: userGuide.pdf
            
  
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Project_Proposal.qmd
        text: Project Proposal
      
      - href: Poster.qmd
        text: Poster
        
      - text: "Analysis"
        menu:
          - text: "Time_series"
            href: "Analysis/Time_series/Time_series.html"
          - text: "EDA"
            href: "Analysis/EDA/EDA.html"
          - text: "Predictive_Analysis"
            href: "Analysis/Predictive_Analysis/Predictive_Analysis.html"
        
    right:  
      - text: "Prof Kam Click This :D"
        href: Music.html

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual
