project:
  type: website

website:
  title: "ISSS608_Final_Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - about.qmd
     
      - href: Project_Proposal.qmd
        text: Project Proposal
      
      - text: "Analysis"
        menu:
          - text: "Time_series" 
            href: "Time_series/Time_series"
        
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

